### ISSUE TITLE
Emojis not showing on low definition devices?

### ISSUE THREAD

**Issue by ikarixdev** [dbaq/angular-emoji-filter-hd#12]
I tested the filter on Samsung SII and emojis are not showing.

**Comment by dbaq** [comment]
Hey @ikarixdev,

Interesting, the decision of displaying the hi/low definition file is made here: https://github.com/dbaq/angular-emoji-filter-hd/blob/master/dist/emoji.scss#L9-L21

You should play a little bit with these media queries and let me know if something is missing. I don't have any Samsung SII to test.

Thank you.

**Comment by dbaq** [comment]
Closing this one since it's been more than a year. Feel free to re-open it if it is still an issue.
