### ISSUE TITLE
Mismatching CSS classes

### ISSUE THREAD

**Issue by filipmandaric** [dbaq/angular-emoji-filter-hd#5]
The emojis black_square and white_square correspond to the incorrectly named CSS classes emoji_black_large_square and emoji_white_large_square. Should be emoji_black_square and emoji_white_square I think. Otherwise great work, thanks.

**Comment by dbaq** [comment]
Hey @filipmandaric, thanks for reporting the issue.

Fixed via https://github.com/dbaq/angular-emoji-filter-hd/commit/82679ac6ef87473ef9be5a10f99784f1b72379c9

**Comment by filipmandaric** [comment]
No problem, thanks!
