### ISSUE TITLE
Support for emoji aliases

### ISSUE THREAD

**Issue by mskec** [dbaq/angular-emoji-filter-hd#8]
Hi,

I used this repo in one project I work on.

What we are missing is ability to add aliases for emojis.
What I mean is to make it possible to write `:)` and make it display `:smile:` (:smile:). Or to write `<3` and to make it display `:heart:` (:heart:).

Would you be open to pull request with this support?

Martin

**Comment by dbaq** [comment]
Hey @mskec,

That's a good idea but I don't have any time available right now. Feel free to open a PR, I would happy to merge it.

Cheers
